-- Generated by Omagen. Window style: border=solid border_size=1 shape=soft spacing=compact depth=native inactive=native.
local active_border_color = "rgb(7e7baa)"
local inactive_border_color = "rgb(7a7a7a)"

hl.config({
  general = {
    col = { active_border = active_border_color, inactive_border = inactive_border_color },
    border_size = 1,
    gaps_in = 4, gaps_out = 5,
  },
  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },
  decoration = {
    rounding = 3, rounding_power = 3,
  },
})
